load("//perl:platforms.bzl", "PLATFORMS")

exports_files([
    "LICENSE.txt",
    "MODULE.bazel",
    "version.bzl",
])

[
    alias(
        name = name,
        actual = "//perl:{}".format(name),
        visibility = ["//visibility:public"],
    )
    for name in [
        "current_toolchain",
        "toolchain_type",
    ] + [
        "perl_{}_toolchain".format(platform.legacy_name)
        for platform in PLATFORMS
        if platform.legacy_name
    ]
]
