"""The pinned Perl release. Generated by //tools/update_perl_version;
do not edit by hand. See CONTRIBUTING.md.
"""

# Where the release archives are downloaded from.
PERL_RELEASES_URL = "https://github.com/UebelAndre/portable-perl/releases/download"

PERL_BUILD = "20260929"

PERL_VERSION = "5.44.0"

# Release platform name -> integrity of perl-<PERL_VERSION>-<platform>.tar.xz.
PERL_INTEGRITY = {
    "aarch64-linux-gnu": "sha256-Kl91TsCoItX5Wp3VoyqsszFvrGSn0uVD57Strr+b8Es=",
    "aarch64-linux-musl": "sha256-t8hgfgL2M0sT3CEdTTtreWEvDb53TxBWa0Nx9PhUTGI=",
    "aarch64-linux-musl-static": "sha256-MS2ewgGV0CYkJaL62EglE1BayW+myxaRtwpjDevS+uI=",
    "aarch64-macos": "sha256-+qFWzaMcV1PQKrCwRrK1VQq+OV46ms9DGlWS0MeDPF0=",
    "aarch64-windows-msvc": "sha256-vH9ilFw7WU4+gueQTpsTX4x+xSpLHdTHoUbfRp47lJI=",
    "x86_64-linux-gnu": "sha256-yaoQckCTJyYU9cCXkPH3NaX8LvwuKroiuMX7rLqR4pk=",
    "x86_64-linux-musl": "sha256-KugjyEsCFM8pW6XxqTu5V7qUhAVb4rdVmud96WKElgM=",
    "x86_64-linux-musl-static": "sha256-Ye5bNrI+debOBDn5N82P+FUBNvutrXzz3L2TbxIPwDk=",
    "x86_64-macos": "sha256-m6jQIVBr5g0IshZPQYMSh7dYfsFwQDu+nKVAQvWfG5w=",
    "x86_64-windows-gnu": "sha256-LLLgbdKBzMFPL4FFlmSS7yiEXddFZoUgMQ9CSeA74YA=",
    "x86_64-windows-msvc": "sha256-IMzzUf3Nv7sUVFjjQMJRyShYkKzDpGdaAjpU82R+6M4=",
}
