#!/usr/bin/env perl
#
# Regenerates perl/private/perl_version.bzl from a release's SHA256SUMS. See
# CONTRIBUTING.md, "Updating the pinned Perl".
#
# Runs either as `bazel run //tools/update_perl_version` or directly as
# `perl tools/update_perl_version/update_perl_version.pl`. Only core modules
# are used so any perl 5 will do; the latter is how the pin gets repaired when
# the pinned toolchain itself cannot be downloaded.
use strict;
use warnings;

use Cwd qw(realpath);
use File::Basename qw(dirname);
use File::Spec;
use Getopt::Long qw(GetOptions);
use HTTP::Tiny;
use MIME::Base64 qw(encode_base64);

my $usage = "usage: $0 --build YYYYMMDD[.N] [--version X.Y.Z] [--releases URL]\n";

my $build;
my $version;
my $releases = 'https://github.com/UebelAndre/portable-perl/releases/download';
GetOptions(
    'build=s'    => \$build,
    'version=s'  => \$version,
    'releases=s' => \$releases,
) or die $usage;
die $usage unless defined $build;
die "build id must be YYYYMMDD or YYYYMMDD.N, got '$build'\n"
    unless $build =~ /^\d{8}(?:\.\d+)?$/;
$releases =~ s{/+$}{};

my $url = "$releases/$build/SHA256SUMS";
my $sums = fetch($url);

# Lines look like: <sha256>  perl-5.44.0-x86_64-linux-gnu.tar.xz
# Bazel takes checksums in Subresource Integrity form: the hash name, a dash,
# and the raw digest base64 encoded.
my %sha;
for my $line (split /\n/, $sums) {
    next unless $line =~ /^([0-9a-f]{64})\s+\*?perl-(\d+\.\d+\.\d+)-(\S+)\.tar\.xz$/;
    $sha{$2}{$3} = 'sha256-' . encode_base64(pack('H*', $1), '');
}
die "no perl archives listed in $url\n" unless %sha;

my @versions = sort keys %sha;
if (!defined $version) {
    die "build $build carries several Perl versions (@versions); pass --version\n"
        if @versions > 1;
    $version = $versions[0];
}
die "Perl $version is not in build $build (available: @versions)\n"
    unless $sha{$version};

# Under `bazel run` the script executes from its runfiles tree; the file to
# rewrite is in the source tree, which Bazel points at with
# BUILD_WORKSPACE_DIRECTORY. Run directly, the workspace root is two levels up
# from this script (tools/update_perl_version/).
my $workspace = $ENV{BUILD_WORKSPACE_DIRECTORY}
    // realpath(File::Spec->catdir(dirname(__FILE__), File::Spec->updir, File::Spec->updir));
my $out = File::Spec->catfile($workspace, qw(perl private perl_version.bzl));
die "$out does not exist; is this the rules_perl checkout?\n" unless -f $out;

my @platforms = sort keys %{ $sha{$version} };
open my $fh, '>', $out or die "cannot write $out: $!\n";
print {$fh} <<"HEADER";
"""The pinned Perl release. Generated by //tools/update_perl_version;
do not edit by hand. See CONTRIBUTING.md.
"""

# Where the release archives are downloaded from.
PERL_RELEASES_URL = "$releases"

PERL_BUILD = "$build"

PERL_VERSION = "$version"

# Release platform name -> integrity of perl-<PERL_VERSION>-<platform>.tar.xz.
PERL_INTEGRITY = {
HEADER
print {$fh} qq(    "$_": "$sha{$version}{$_}",\n) for @platforms;
print {$fh} "}\n";
close $fh or die "cannot close $out: $!\n";

printf "pinned build %s, perl %s, %d platforms -> %s\n", $build, $version, scalar @platforms, $out;

# GETs a URL and returns the body. HTTP::Tiny is core, but speaking https
# needs IO::Socket::SSL and Net::SSLeay, which are not, and are absent from the
# pinned toolchain. Use it when it can, otherwise fall back to curl.
sub fetch {
    my ($url) = @_;
    if (HTTP::Tiny->can_ssl) {
        my $res = HTTP::Tiny->new->get($url);
        return $res->{content} if $res->{success};
        die "failed to fetch $url: $res->{status} $res->{reason}\n";
    }
    my $body = qx(curl --fail --silent --show-error --location "$url");
    die "failed to fetch $url (no IO::Socket::SSL for HTTP::Tiny, and curl failed)\n"
        if $? != 0;
    return $body;
}
